name: Deploy App3 to Render
on:
  push:
    paths:
      - 'apps/app3/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Render Deploy Hook
        run: |
          curl "$RENDER_DEPLOY_HOOK_URL_APP3"
        env:
          RENDER_DEPLOY_HOOK_URL_APP3: ${{ secrets.RENDER_DEPLOY_HOOK_URL_APP3 }}