name: Deploy App5 to Render
on:
  push:
    paths:
      - 'apps/app5/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Render Deploy Hook
        run: |
          curl "$RENDER_DEPLOY_HOOK_URL_APP5"
        env:
          RENDER_DEPLOY_HOOK_URL_APP5: ${{ secrets.RENDER_DEPLOY_HOOK_URL_APP5 }}